apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: quarantine
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      quarantine: "true"
  policyTypes:
  - Egress

