apiVersion: v1
kind: Service
metadata:
  name: statuspage
  namespace: {{ .Release.Namespace  }}
spec:
  ports:
  - nodePort: {{ .Values.service.nodePort }}
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webserver
  type: NodePort
