apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html-content-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: manual-storage
  #selector:
  #  matchLabels:
  #    release: "stable"
  #  matchExpressions:
  #    - {key: environment, operator: In, values: [dev]}
