apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: {{ .Release.Namespace }}
  labels:
    app: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
      quarantine: "true"
  template:
    metadata:
      labels:
        app: webserver
        quarantine: "true"
    spec:
      containers:
      - name: webserver
        image: {{ .Values.webserver.image }}:{{ .Values.webserver.label }}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: static-content
          mountPath: {{ .Values.webserver.contentPath }}
      volumes:
        - name: static-content
          persistentVolumeClaim:
            claimName: html-content-pvc 
