webserver:
  image: nginx
  label: 1.21.4-alpine
  contentPath: /usr/share/nginx/html

duckdns:
  schedule: "*/5 * * * *"
  image: curlimages/curl
  label: "7.80.0"
  domain: <your duckdns.org name>
  secretName: duckdns
 
service:
  nodePort: 30008

statuspage:
  pageId: <your page id>
  bandwidth:
    metricId: <your metric id>
    schedule: "0 */3 * * *"
    image: "fuele/internet-statuspage:1.0.0-aarch64"
  latency:
    metricId: <your metric id>
    schedule: "* * * * *"
    image: "fuele/internet-statuspage:1.0.0-aarch64"
    targetHost: "1.1.1.1"
